import = ["/Users/josef.podany/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = true

[debug]
persistent_logging = false

[font]
size = 13

[font.bold]
family = "B612 Mono"
# family = "CommitMono-jsfpdn-2-thinner"
style = "Bold"

[font.bold_italic]
family = "B612 Mono"
# family = "CommitMono-jsfpdn-2-thinner"
style = "Bold Italic"

[font.italic]
family = "B612 Mono"
# family = "CommitMono-jsfpdn-2-thinner"
style = "Regular Italic"

[font.normal]
family = "B612 Mono"
# family = "CommitMono-jsfpdn-2-thinner"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
key = "Comma"
mods = "Command"

[keyboard.bindings.command]
args = ["-c", "open ~/.config/alacritty/alacritty.yml"]
program = "sh"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002%"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\""
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002x"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002o"
key = "Return"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00020"
key = "Key0"
mods = "Command"

[shell]
args = ["-l", "-c", "tmux attach 2>/dev/null || tmux -f ~/.config/.tmux.conf"]
program = "/bin/zsh"
